### ISSUE TITLE
[BUG] (Sometimes) DL queue stays empty if adding a episode to the queue

### ISSUE THREAD

**Issue by progithub2** [OpenSTDL/CrunchyDL#38] opened 2024-06-24 18:12 UTC
After send Episode to Download Queue remains empty
![cr4-1](https://github.com/OpenSTDL/CrunchyDL/assets/166246771/7c138836-e148-4ff0-b74f-ab540a682ef9)

**Comment by stratuma** [comment] 2024-06-24 19:28
It looks like the downloader didn't load up right on your part, do you have a antivirus that blocks something maybe?

**Comment by progithub2** [comment] 2024-06-25 17:53
It doesn't matter whether the virus scanner is on or off, it makes no difference...

I also tried uninstalling (1.2.3) and installed my first version 1.1.9...

The download is running so far, but you can't see anything...

Nobody else has the same problem?

**Comment by progithub2** [comment] 2024-06-25 18:34
maybe I've found an approach... 

The error only occurs in a classic (which was newly added).... 

May you know it.... Saber Rider ;-)

On Hensuki it works....

![cr4-2](https://github.com/OpenSTDL/CrunchyDL/assets/166246771/f1a020da-f3a0-40c5-89f7-819d2422da9e)

Could you take a look on this behavior?

**Comment by stratuma** [comment] 2024-06-25 18:37
I can't reproduce it, I tried several animes and I never got that behaviour.
It never got reported too.

**Comment by progithub2** [comment] 2024-06-25 18:43
Did you've tried Saber Rider and the Starsheriffs?

**Comment by stratuma** [comment] 2024-06-25 18:45
> Did you've tried Saber Rider and the Starsheriffs?

Yeah, I don't get this behaviour

**Comment by stratuma** [comment] 2024-06-28 00:38
Maybe someone with the same issue will answer in this issue. idk how to reproduce it, it could be everything.

**Comment by stratuma** [comment] 2024-07-02 23:59
Fixed in v1.2.4

**Closed by stratuma** 2024-07-02 23:59 UTC
Labels: bug, on hold
