### ISSUE TITLE
[BUG] Hardsub option wont dissapear

### ISSUE THREAD

**Issue by x3inspire** [OpenSTDL/CrunchyDL#50] opened 2024-07-03 13:50 UTC
Hi, the latest version hardsub option not dissaper after clicked EN (sub). I clicked En (sub) and the option keep stick and i cannot click "Add to download". But when i choose EN (sub) hardsub it auto download at the behind.

![image](https://github.com/OpenSTDL/CrunchyDL/assets/4635825/7c15a20f-b677-4269-a0e2-37fbadfaacb4)

**Comment by stratuma** [comment] 2024-07-03 13:51
Thx for the bugreport.
For now just click on hardsub again, it will disappear.
I will fix it later

**Comment by x3inspire** [comment] 2024-07-03 13:56
Possible to add sub setting under apps setting like hama downloader?

![image](https://github.com/OpenSTDL/CrunchyDL/assets/4635825/89dd2637-7061-4f7b-89df-d2af4e555505)

**Comment by stratuma** [comment] 2024-07-03 18:02
> Possible to add sub setting under apps setting like hama downloader?
> 
> ![image](https://private-user-images.githubusercontent.com/4635825/345450676-89dd2637-7061-4f7b-89df-d2af4e555505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMzAwNTcsIm5iZiI6MTcyMDAyOTc1NywicGF0aCI6Ii80NjM1ODI1LzM0NTQ1MDY3Ni04OWRkMjYzNy03MDYxLTRmN2ItODlkZi1kMmFmNGU1NTU1MDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMTgwMjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTljZDhhMmVjNTM1OTM4YTk2NTRkNGM2MTc2YzgzN2Y5Nzk0NDdlMmJiNGQxZGNlMzQ1ZDVhYmQwMzhkNmQxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hvGubtz55bdfyI3vQhgsAggT9lpJqdtFnVxjtzJf1Hg)

Yeah I can implement it.

**Comment by stratuma** [comment] 2024-07-11 13:21
Fixed in v1.2.5

**Closed by stratuma** 2024-07-11 13:21 UTC
Labels: bug, waiting for release

**Comment by acteiaa** [comment] 2024-07-11 14:41
![image](https://github.com/OpenSTDL/CrunchyDL/assets/163225023/5f56b366-daf6-4f0f-b998-50f14a7ebf0e)
When opting for PT hardsub, this happens, and for the record, this new hardsub and harddub system is terrible; the old system was better, or it could be like hama. The problem is that there is no option not to use this new system, as the old versions are obsolete.

**Comment by stratuma** [comment] 2024-07-11 14:43
> ![image](https://private-user-images.githubusercontent.com/163225023/347865413-5f56b366-daf6-4f0f-b998-50f14a7ebf0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDkyNjcsIm5iZiI6MTcyMDcwODk2NywicGF0aCI6Ii8xNjMyMjUwMjMvMzQ3ODY1NDEzLTVmNTZiMzY2LWRhZjYtNGYwZi1iOTk4LTUwZjE0YTdlYmYwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxNDQyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGQ2NjlkYzRiYWU1NzUzOWI5ODhmMTQ1NzYxMjU0MWVmMGMxOGY2OWM4YTU2YjhiYmJhOTg5YzNmMjcyMjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1D2YNzUnvJDwCgI2_EDtufLuSKJgFP0QcYdo1fU4z1g) When opting for PT hardsub, this happens, and for the record, this new hardsub and harddub system is terrible; the old system was better, or it could be like hama. The problem is that there is no option not to use this new system, as the old versions are obsolete.

I can't even work 2 hours without crunchyroll changing any of theyr shit.

**Comment by acteiaa** [comment] 2024-07-11 14:45
The old hama program works to download subtitles, I use it to download them since the ones here have problems

**Comment by acteiaa** [comment] 2024-07-11 17:10
I can't download anything, an error always occurs.🥲

**Comment by stratuma** [comment] 2024-07-11 19:18
> I can't download anything, an error always occurs.🥲

Fixed in v1.2.6
